version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      minor-and-patch:
        update-types:
          - "patch"
          - "minor"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Tokyo"
